apiVersion: apps/v1
kind: Deployment
metadata:
  name: dropwizard-app-deployment
  labels:
    app: rest-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dropwizard-app
  template:
    metadata:
      labels:
        app: dropwizard-app
    spec:
      containers:
      - name: dropwizard-app
        image: demorepository.azurecr.io/dropwizard-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dropwizard-app-service
spec:
  selector:
    app: dropwizard-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001